version: '3'
services:
  puppeteer:
    build: app
    image: puppeteer-dev:1.0
    container_name: puppeteer
    environment:
      NODE_ENV: development
      #NODE_ENV: production
    env_file:
      - .env
      - ./app/.env
    volumes:
      - ./app:/app
      - node_modules:/app/node_modules

volumes:
  node_modules:
    driver: 'local'
